name: ci
on:
  push:
    branches:
      - master
    paths:
      - src
      - test
      - package.json
      - .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test on Node 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM setup
        uses: pnpm/action-setup@v3

      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
