name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 16
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # - uses: bahmutov/npm-install@v1
      - run: npm run lint:ts
      - run: npm run build
