name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # - uses: bahmutov/npm-install@v1
      - run: npm install
      - run: npm run lint:ts
      - run: npm run build
